In [1]:
import numpy
from sklearn import preprocessingprocessing

In [3]:
input_data = numpy.array([[3, -1, 3, -6.4], [0, 3, -1.3, 4.1], [1, 2.3, -2.3, -4.9]])

** Mean Removal **

In [4]:
std_data = preprocessing.scale(input_data)

In [6]:
print("Mean = ", std_data.mean(axis = 0))

Mean =  [ 5.55111512e-17 -5.55111512e-17  7.40148683e-17  3.70074342e-17]


In [8]:
print("Std. Dviation", std_data.std(axis=0))

Std. Dviation [1. 1. 1. 1.]


** Scaling **

In [11]:
data_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_data = data_scaler.fit_transform(input_data)

In [12]:
print("Scaled data = ", scaled_data)

Scaled data =  [[1.         0.         1.         0.        ]
 [0.         1.         0.18867925 1.        ]
 [0.33333333 0.825      0.         0.14285714]]


** Normalization **

In [20]:
normalized_data1 = preprocessing.normalize(input_data, "l1")

In [21]:
print("Normalized data", normalized_data1)

Normalized data [[ 0.2238806  -0.07462687  0.2238806  -0.47761194]
 [ 0.          0.35714286 -0.1547619   0.48809524]
 [ 0.0952381   0.21904762 -0.21904762 -0.46666667]]


In [22]:
normalized_data2 = preprocessing.normalize(input_data, "l2")

In [23]:
print("Normalized data", normalized_data2)

Normalized data [[ 0.3874275  -0.1291425   0.3874275  -0.826512  ]
 [ 0.          0.57207755 -0.24790027  0.78183932]
 [ 0.16762393  0.38553503 -0.38553503 -0.82135723]]


** Binarization ** 

In [24]:
binarized_data = preprocessing.binarize(input_data, threshold=1.4)

In [ ]:
print("Binarized data = ", bi)