In [1]:
import numpy as np

In [ ]:
str1 = 'saket\'s msg''

In [2]:
arr = np.array( [[ 1, 2, 3], [ 4, 2, 5]])
# Converting list into array

In [3]:
print("Array is of type: ", type(arr)) 

Array is of type:  <class 'numpy.ndarray'>


In [4]:
print("No. of dimensions: ", arr.ndim) 

No. of dimensions:  2


In [5]:
print("Shape of array: ", arr.shape)

Shape of array:  (2, 3)


In [6]:
print("Size of array: ", arr.size) 
arr

Size of array:  6


array([[1, 2, 3],
       [4, 2, 5]])

In [7]:
print("Array stores elements of type: ", arr.dtype) 

Array stores elements of type:  int32


In [8]:
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float') 
print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [9]:
b = np.array((1 , 3, 2), dtype='float') 
print ("\nArray created using passed tuple:\n", b) 


Array created using passed tuple:
 [1. 3. 2.]


In [13]:
c = np.zeros((3, 4), dtype='int32') 
print ("\nAn array initialized with all zeros:\n", c)


An array initialized with all zeros:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [14]:
d = np.full((3, 3), 1, dtype = 'complex') 
print ("\nAn array initialized with all 6s. Array type is complex:\n",d) 


An array initialized with all 6s. Array type is complex:
 [[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


In [17]:
e = np.random.random((2, 2))
print ("\nA random array:\n", e)


A random array:
 [[0.14737979 0.07382336]
 [0.94492456 0.8013114 ]]


In [19]:
f = np.arange(0, 30, 5)                       # start : end : step_size
print ("\nA sequential array with steps of 5:\n", f) 


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [20]:
g = np.linspace(0, 5, 11)          # start : end : total_no_of_points
print ("\nA sequential array with 10 values between 0 and 5:\n", g) 


A sequential array with 10 values between 0 and 5:
 [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [18]:
arr = np.array([[1, 2, 3, 4], 
                [5, 2, 4, 2], 
                [1, 2, 0, 1]])  

In [21]:
newarr = arr.reshape(2, 2, 3) 
  
print ("\nOriginal array:\n", arr) 
print ("\nReshaped array:\n", newarr) 


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
flarr = arr.flatten() 
  
print ("\nOriginal array:\n", arr) 
print ("\nFatterned array:\n", flarr)


Original array:
 [[1 2 3]
 [4 5 6]]

Fatterned array:
 [1 2 3 4 5 6]


In [24]:
arr = np.array([[-1, 2, 0, 4], 
                [4, -0.5, 6, 0], 
                [2.6, 0, 7, 8], 
                [3, -7, 4, 2.0]]) 
  
temp = arr[:2, ::2] 
print ("Array with first 2 rows and alternate columns(0 and 2):\n", temp) 

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [25]:
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]] 
print ("\nElements at indices (0, 3), (1, 2), (2, 1), (3, 0):\n", temp) 


Elements at indices (0, 3), (1, 2), (2, 1), (3, 0):
 [4. 6. 0. 3.]


In [26]:
cond = arr > 0           # cond is a boolean array 
temp = arr[cond] 
print ("\nElements greater than 0:\n", temp) 


Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [27]:
a = np.array([1, 2, 5, 3]) 

In [28]:
print ("Adding 1 to every element:", a+1) 

Adding 1 to every element: [2 3 6 4]


In [29]:
print ("Subtracting 3 from each element:", a-3) 

Subtracting 3 from each element: [-2 -1  2  0]


In [30]:
print ("Multiplying each element by 10:", a*10) 

Multiplying each element by 10: [10 20 50 30]


In [31]:
print ("Squaring each element:", a**2) 

Squaring each element: [ 1  4 25  9]


In [32]:
a *= 2
print ("Doubled each element of original array:", a) 

Doubled each element of original array: [ 2  4 10  6]


In [33]:
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]]) 
print ("\nOriginal array:\n", a) 
print ("Transpose of array:\n", a.T) 


Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [34]:
arr = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]])

In [35]:
print ("Largest element is:", arr.max()) 

Largest element is: 9


In [36]:
print ("Row-wise maximum elements:", arr.max(axis = 1)) 

Row-wise maximum elements: [6 7 9]


In [37]:
print ("Column-wise minimum elements:", arr.min(axis = 0)) 

Column-wise minimum elements: [1 1 2]


In [38]:
print ("Sum of all array elements:", arr.sum()) 

Sum of all array elements: 38


In [39]:
print ("Cumulative sum along each row:\n", arr.cumsum(axis = 1)) 

Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [40]:
a = np.array([[1, 2], [3, 4]]) 
b = np.array([[4, 3], [2, 1]]) 

In [41]:
print ("Array sum:\n", a + b) 

Array sum:
 [[5 5]
 [5 5]]


In [45]:
print ("Array multiplication:\n", a*b) 

Array multiplication:
 [[4 6]
 [6 4]]


In [46]:
print ("Matrix multiplication:\n", a.dot(b)) 

Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [ ]:
a = np.array([0, np.pi/2, np.pi])
a

In [ ]:
print ("Sine values of array elements:", np.sin(a))

In [ ]:
a = np.array([0, 1, 2, 3]) 
print ("Exponent of array elements:", np.exp(a)) 

In [ ]:
print ("Square root of array elements:", np.sqrt(a))

In [ ]:
a = np.array([[1, 4, 2], [3, 4, 6], [0, -1, 5]], dtype='float') 
a

In [ ]:
print ("Array elements in sorted order:\n", np.sort(a)) 

In [ ]:
print ("Array elements in sorted order:\n", np.sort(a, axis=None)) 

In [ ]:
print ("Row-wise sorted array:\n", np.sort(a, axis = 1))

In [ ]:
print ("Column wise sort by applying merge-sort:\n",
       np.sort(a, axis = 0, kind = 'mergesort')) 

In [47]:
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)] 
  
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),  
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)] 
             
arr = np.array(values, dtype = dtypes) 
arr

array([(b'Hrithik', 2009, 8.5), (b'Ajay', 2008, 8.7),
       (b'Pankaj', 2008, 7.9), (b'Aakash', 2009, 9. )],
      dtype=[('name', 'S10'), ('grad_year', '<i4'), ('cgpa', '<f8')])

In [ ]:
print ("\nArray sorted by names:\n", np.sort(arr, order = 'name')) 
              
print ("Array sorted by grauation year and then cgpa:\n", 
       np.sort(arr, order = ['grad_year', 'cgpa'])) 